# Generated by elixir_baseline. Do not edit: a change made here is lost the
# next time the file is generated. Change the template it comes from instead.
#
# Credo's own default config (deps/credo/.credo.exs) is the baseline. This file
# records only the deviations, so upgrading Credo brings new default checks with
# it. Don't use `checks: %{enabled: ...}` here. It would replace the Credo,
# which means newly added Credo checks wouldn't automatically be applied.
#
# `extra` is merged with Keyword.merge/2 on the check module, so it both
# enables a check Credo disables by default and overrides the options of one
# that Credo already enables.
%{
  configs: [
    %{
      name: "default",
      strict: true,
      files: %{
        included: [
          "lib/",
          "src/",
          "storybook/",
          "test/",
          "apps/*/lib/",
          "apps/*/src/",
          "apps/*/storybook/",
          "apps/*/test/"
        ],
        excluded: [~r"/_build/", ~r"/deps/", ~r"/node_modules/"]
      },
      checks: %{
        extra: [
          {Credo.Check.Readability.BlockPipe, []},
          {Credo.Check.Readability.OneArityFunctionInPipe, []},
          {Credo.Check.Readability.SingleFunctionToBlockPipe, []},
          {Credo.Check.Readability.SinglePipe, []},
          {Credo.Check.Readability.StrictModuleLayout, []},
          {Credo.Check.Readability.WithCustomTaggedTuple, []},
          {Credo.Check.Refactor.DoubleBooleanNegation, []},
          {Credo.Check.Refactor.FilterReject, []},
          {Credo.Check.Refactor.MapMap, []},
          {Credo.Check.Refactor.PassAsyncInTestCases, []},
          {Credo.Check.Refactor.PipeChainStart, []},
          {Credo.Check.Refactor.RejectFilter, []},
          {Credo.Check.Warning.MapGetUnsafePass, []},
          {Credo.Check.Warning.WrongTestFileExtension, []},
          {Credo.Check.Readability.MaxLineLength,
           [priority: :low, max_length: 80]}
        ]
      }
    }
  ]
}
